test:
  _target_: src.datasets.VCTKDataset
  dataset_split_file: "src/VCTK_split_as_papers/test.txt"
  vctk_wavs_dir_lr: /opt/software/datasets/VCTK/VCTK4kresampled
  vctk_wavs_dir_hr: /opt/software/datasets/VCTK/VCTK16kresampled
  initial_sr: 4000
  target_sr: 16000
  segment_size: 8192
  device: ${inferencer.device}
  split: True
  mode: 'test'
