defaults:
  - model: model
  - metrics: metrics
  - datasets: test_dataset
  - dataloader: test_loader
  - _self_
inferencer:
  device_tensors: ["wav_lr", "wav_hr", "melspec_lr", "melspec_hr"]
  device: auto
  save_path: "inference_dir"
  seed: 1
  from_pretrained: null