_target_: src.model.CoMBD
combd_h_u : [
  [16, 64, 256, 1024, 1024, 1024],
  [16, 64, 256, 1024, 1024, 1024],
  [16, 64, 256, 1024, 1024, 1024]
]
combd_d_k : [
  [7, 11, 11, 11, 11, 5],
  [11, 21, 21, 21, 21, 5],
  [15, 41, 41, 41, 41, 5]
]
combd_d_s : [
  [1, 1, 4, 4, 4, 1],
  [1, 1, 4, 4, 4, 1],
  [1, 1, 4, 4, 4, 1]
]
combd_d_d : [
  [1, 1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1, 1]
]
combd_d_g : [
  [1, 4, 16, 64, 256, 1],
  [1, 4, 16, 64, 256, 1],
  [1, 4, 16, 64, 256, 1]
]
combd_d_p : [
  [3, 5, 5, 5, 5, 2],
  [5, 10, 10, 10, 10, 2],
  [7, 20, 20, 20, 20, 2]
]

combd_op_f : [1, 1, 1]
combd_op_k : [3, 3, 3]
combd_op_g : [1, 1, 1]