_target_: src.model.discriminators.CoMBD
h_u : [
  [16, 64, 256, 1024, 1024, 1024],
  [16, 64, 256, 1024, 1024, 1024],
  [16, 64, 256, 1024, 1024, 1024]
]
d_k : [
  [7, 11, 11, 11, 11, 5],
  [11, 21, 21, 21, 21, 5],
  [15, 41, 41, 41, 41, 5]
]
d_s : [
  [1, 1, 4, 4, 4, 1],
  [1, 1, 4, 4, 4, 1],
  [1, 1, 4, 4, 4, 1]
]
d_d : [
  [1, 1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1, 1]
]
d_g : [
  [1, 4, 16, 64, 256, 1],
  [1, 4, 16, 64, 256, 1],
  [1, 4, 16, 64, 256, 1]
]
d_p : [
  [3, 5, 5, 5, 5, 2],
  [5, 10, 10, 10, 10, 2],
  [7, 20, 20, 20, 20, 2]
]

op_f : [1, 1, 1]
op_k : [3, 3, 3]
op_g : [1, 1, 1]

pqmf_config:
  lv1: [2, 256, 0.25, 10.0]
  lv2: [4, 192, 0.13, 10.0]
