_target_: src.model.SBD
filters: [[64, 128, 256, 256, 256],[64, 128, 256, 256, 256],[64, 128, 256, 256, 256],[32, 64, 128, 128, 128]]
strides: [[1, 1, 3, 3, 1], [1, 1, 3, 3, 1], [1, 1, 3, 3, 1], [1, 1, 3, 3, 1]]
kernel_sizes: [
  [[7, 7, 7],[7, 7, 7],[7, 7, 7],[7, 7, 7],[7, 7, 7]],
  [[5, 5, 5],[5, 5, 5],[5, 5, 5],[5, 5, 5],[5, 5, 5]],
  [[3, 3, 3],[3, 3, 3],[3, 3, 3],[3, 3, 3],[3, 3, 3]],
  [[5, 5, 5],[5, 5, 5],[5, 5, 5],[5, 5, 5],[5, 5, 5]]
]
dilations: [
  [[5, 7, 11], [5, 7, 11], [5, 7, 11], [5, 7, 11], [5, 7, 11]],
  [[3, 5, 7], [3, 5, 7], [3, 5, 7], [3, 5, 7], [3, 5, 7]],
  [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]],
  [[1, 2, 3], [1, 2, 3], [1, 2, 3], [2, 3, 5], [2, 3, 5]]
]
band_ranges: [[0, 6], [0, 11], [0, 16], [0, 64]]
transpose: [false, false, false, true]
pqmf_params: [16, 256, 0.03, 10.0]
f_pqmf_params: [64, 256, 0.1, 9.0]

segment_size: ${datasets.train.segment_size}
